version: '3.8'

services:
  # Service สำหรับ backend (Node.js)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend-container
    ports:
      - "3002:3002"  # ระบุพอร์ตที่ต้องการให้ container เปิดและเชื่อมต่อกับเครื่องโฮสต์
    depends_on:
      - db  # ระบุว่า backend ขึ้นอยู่กับ service db (PostgreSQL)
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Cpi#123
      - DB_NAME=Disbursement

  # Service สำหรับ frontend (React + Nginx)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend-container
    ports:
      - "8080:80"  # ให้ Nginx รันบนพอร์ต 80
    depends_on:
      - backend  # frontend ขึ้นอยู่กับ backend

  # Service สำหรับ PostgreSQL Database
  db:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Cpi#123
      POSTGRES_DB: Disbursement
    volumes:
      - ./database:/var/lib/postgresql/data  # การเชื่อมต่อกับไฟล์ฐานข้อมูลบนเครื่องโฮสต์
    ports:
      - "5432:5432"  # เชื่อมต่อกับเครื่องโฮสต์ผ่านพอร์ต 5432
