# ใช้ Node.js image
FROM node:18

# ตั้งค่า working directory
WORKDIR /app

# คัดลอกไฟล์ package.json และ package-lock.json ไปที่ container
COPY package*.json ./

# ติดตั้ง dependencies
RUN npm ci

# คัดลอกโค้ดของ backend ไปยัง container
COPY . .

# พอร์ตที่แอปฟัง
EXPOSE 3002

# คำสั่งในการรันแอป
CMD ["node", "server1.js"]
