name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # เปลี่ยนเป็น Ubuntu เพื่อให้รองรับ Docker ได้ดีขึ้น

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # อัปเดตเป็น v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3  # อัปเดตเป็น v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile.backend
          push: true
          tags: sxpxii/myproject-backend:latest  # เปลี่ยนจาก myusername/project-backend เป็น sxpxii/myproject-backend

      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.frontend
          push: true
          tags: sxpxii/myproject-frontend:latest  # เปลี่ยนจาก myusername/project-fullstack-cpi เป็น sxpxii/myproject-frontend
